dataset:
  name: california_housing
  subset_size: 200
  train_test_ratio: 0.8
alignment:
  type: unaligned
  unalignment_ratio: 0.8
model:
  num_clients: 2
  embedding_size: 8
  mixup_strategy: mean_mixup
  client_models:
  - hidden_layers:
    - 12
    - 6
    learning_rate: 0.001
    model_type: mlp
  - hidden_layers:
    - 12
    - 6
    learning_rate: 0.001
    model_type: mlp
  top_model:
    hidden_layers:
    - 24
    - 12
    learning_rate: 0.001
    aggregate_fn: null
training:
  n_epochs: 100
  batch_size: 4
  device: cuda
  wandb:
    enabled: false
    project: VFL-Regression
    entity: ayushferro123-iit-kharagpur
    name: experiment
feature_distribution: null
