exp: 0
dataset:
  name: energy
  subset_size: 160
  train_test_ratio: 0.8
alignment:
  type: aligned
  unalignment_ratio: 0.2
model:
  num_clients: 2
  embedding_size: 16
  mixup_strategy: mean_mixup
  client_models:
  - hidden_layers:
    - 8
    - 16
    learning_rate: 0.001
    model_type: mlp
  - hidden_layers:
    - 8
    - 16
    learning_rate: 0.001
    model_type: mlp
  top_model:
    hidden_layers:
    - 32
    - 16
    learning_rate: 0.001
training:
  n_epochs: 100
  batch_size: 8
  device: cpu
  wandb:
    enabled: false
    project: dummy1
    entity: dummy2
    name: dummy3
feature_distribution: null
